version: '3.8'

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: 247386628655.dkr.ecr.us-west-2.amazonaws.com/task-manager
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - laravel
  npm-dev:
    image: node:18
    container_name: npm-dev
    working_dir: /var/www
    ports:
      - "3000:3000"
    command: npm run dev 
    volumes:
      - .:/var/www
    networks:
      - laravel

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: mysql
    tty: true
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: laravel
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  webserver:
    platform: linux/amd64
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
